FROM golang:1.3

COPY . /go/src/github.com/docker/datakit/
WORKDIR /go/src/github.com/docker/datakit/
RUN go get -d ./hooks/datakit-gh/...
WORKDIR /go/src/github.com/docker/datakit/hooks/datakit-gh
RUN go build
ENTRYPOINT ["./datakit-gh"]
