FROM ocaml/opam-dev@sha256:64dc0522876ebbd27b186e3ba955ae5ab864ace580add5b0d1abb8715bdf1bbe
#FROM ocaml/opam-dev:alpine-3.5_ocaml-4.04.0
ENV OPAMERRLOGLEN=0 OPAMYES=1
RUN sudo apk add tzdata aspcud

RUN opam pin add irmin.1.1.0 -n https://github.com/mirage/irmin.git#89196ad17c53b02f333022a87ecc264ec8c06af0
RUN opam pin add irmin-git.1.1.0 -n https://github.com/mirage/irmin.git#89196ad17c53b02f333022a87ecc264ec8c06af0
RUN opam pin add irmin-unix.1.1.0 -n https://github.com/mirage/irmin.git#89196ad17c53b02f333022a87ecc264ec8c06af0

RUN opam pin add -yn protocol-9p.0.11.0 'https://github.com/mirage/ocaml-9p.git#v0.11.0'
RUN opam pin add -yn protocol-9p-unix.0.11.0 'https://github.com/mirage/ocaml-9p.git#v0.11.0'

RUN opam depext -i asl win-eventlog camlzip alcotest mtime mirage-flow hvsock \
    git irmin irmin-unix lwt protocol-9p-unix tyxml redis multipart-form-data \
    pbkdf tls prometheus-app github git session irmin irmin-unix cmdliner \
    webmachine alcotest

ADD . /home/opam/datakit
RUN sudo chown opam /home/opam/datakit
RUN opam pin add -k git datakit-client.dev /home/opam/datakit -y
RUN opam pin add -k git datakit-client-9p.dev /home/opam/datakit -y
RUN opam pin add -k git datakit-server.dev /home/opam/datakit -y
RUN opam pin add -k git datakit-server-9p.dev /home/opam/datakit -y
RUN opam pin add -k git datakit-github.dev /home/opam/datakit -y
RUN opam pin add -k git datakit.dev /home/opam/datakit -y

RUN opam pin add -k git datakit-ci.dev /home/opam/datakit -yt

VOLUME /secrets
