FROM ocaml/opam-dev@sha256:1dd4440b3e5f182f705cb5a74f9d4e860c2842b45ed72c199de89a894d13f522
#FROM ocaml/opam-dev:alpine-3.5_ocaml-4.04.0

ENV OPAMERRLOGLEN=0 OPAMYES=1
RUN sudo apk add tzdata aspcud

RUN opam depext -ui lwt inotify alcotest conf-libev lambda-term cmdliner \
    github protocol-9p rresult prometheus-app asl win-eventlog mtime hex \
    github-hooks hvsock irmin-watcher git irmin

COPY check-libev.ml /tmp/check-libev.ml
RUN opam config exec -- ocaml /tmp/check-libev.ml

# cache opam install of dependencies
COPY datakit.opam /home/opam/src/datakit/datakit.opam
COPY datakit-client.opam /home/opam/src/datakit/datakit-client.opam
COPY datakit-client-9p.opam /home/opam/src/datakit/datakit-client-9p.opam
COPY datakit-client-git.opam /home/opam/src/datakit/datakit-client-git.opam
COPY datakit-server.opam /home/opam/src/datakit/datakit-server.opam
COPY datakit-server-9p.opam /home/opam/src/datakit/datakit-server-9p.opam
COPY datakit-github.opam /home/opam/src/datakit/datakit-github.opam
COPY datakit-bridge-github.opam /home/opam/src/datakit/datakit-bridge-github.opam
RUN opam pin add datakit.dev /home/opam/src/datakit -yn && \
    opam pin add datakit-server.dev /home/opam/src/datakit -yn && \
    opam pin add datakit-server-9p.dev /home/opam/src/datakit -yn && \
    opam pin add datakit-client.dev /home/opam/src/datakit -yn && \
    opam pin add datakit-client-9p.dev /home/opam/src/datakit -yn && \
    opam pin add datakit-client-git.dev /home/opam/src/datakit -yn && \
    opam pin add datakit-github.dev /home/opam/src/datakit -yn && \
    opam pin add datakit-bridge-github.dev /home/opam/src/datakit -yn

COPY . /home/opam/src/datakit
RUN sudo chown opam.nogroup -R /home/opam/src/datakit
RUN cd /home/opam/src/datakit && \
    scripts/watermark.sh && \
    git status --porcelain

# FIXME: workaround bug in opam2
RUN opam install datakit
RUN opam install datakit-bridge-github -ytv

RUN sudo cp $(opam config exec -- which datakit-bridge-github) /usr/bin/

USER root

FROM alpine:3.5
RUN apk add --no-cache libev gmp tzdata ca-certificates
EXPOSE 5640
EXPOSE 5641
ENTRYPOINT ["/usr/bin/datakit-bridge-github"]
CMD ["--listen=tcp://0.0.0.0:5641", "-v", "--datakit=tcp:127.0.0.1:5640"]
COPY --from=0 /usr/bin/datakit-bridge-github /usr/bin/datakit-bridge-github
