FROM ocaml/opam-dev@sha256:64dc0522876ebbd27b186e3ba955ae5ab864ace580add5b0d1abb8715bdf1bbe
RUN git -C /home/opam/opam-repository fetch origin && \
    git -C /home/opam/opam-repository reset origin/master --hard && \
    opam update -u
#FROM ocaml/opam:alpine-3.5_ocaml-4.04.0

ENV OPAMERRLOGLEN=0 OPAMYES=1

RUN opam depext -ui lwt alcotest conf-libev

# pin git
RUN opam pin add git.dev --dev -n
RUN opam pin add git-http.dev --dev -n
RUN opam pin add git-mirage.dev --dev -n
RUN opam pin add git-unix.dev --dev -n

# pin irmin
RUN opam pin add irmin.dev --dev -n
RUN opam pin add irmin-fs.dev https://github.com/mirage/irmin.git -n
RUN opam pin add irmin-mem.dev https://github.com/mirage/irmin.git -n
RUN opam pin add irmin-git.dev --dev -n
RUN opam pin add irmin-http.dev --dev -n
RUN opam pin add irmin-mirage.dev --dev -n
RUN opam pin add irmin-unix.dev --dev -n

# cache opam install of dependencies
COPY datakit-client.opam /home/opam/src/datakit/datakit-client.opam
RUN opam pin add datakit-client.dev /home/opam/src/datakit -n

COPY datakit-client-9p.opam /home/opam/src/datakit/datakit-client-9p.opam
RUN opam pin add datakit-client-9p.dev /home/opam/src/datakit -n

COPY datakit-client-git.opam /home/opam/src/datakit/datakit-client-git.opam
RUN opam pin add datakit-client-git.dev /home/opam/src/datakit -n

RUN opam depext datakit-client datakit-client-9p datakit-client-git inotify
RUN opam install datakit-client --deps
RUN opam install irmin-git irmin-watcher git-unix inotify \
    astring logs fmt cstruct protocol-9p-unix cmdliner \
    irmin-mem irmin-git alcotest

# FIXME(samoht): Not sure why this is needed, but it is
RUN opam depext camlzip && opam install ounit camlzip fpath conf-which qcheck \
    fileutils bos qtest

COPY . /home/opam/src/datakit
RUN sudo chown opam.nogroup -R /home/opam/src/datakit
RUN opam update datakit-client datakit-client-9p datakit-client-git

RUN opam install datakit-client.dev -vv -t
RUN opam install datakit-client-9p -vv -t
RUN opam install datakit-client-git.dev -vv -t

RUN sudo mkdir /data && sudo chown opam.nogroup /data && chmod 700 /data && \
    sudo cp $(opam config exec -- which datakit-mount) /usr/bin/datakit-mount

CMD bash -c "/usr/bin/datakit-mount -h $(getent hosts datakit | awk '{print $1}')"; \
    bash
