// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Sharp9P")]
[assembly: AssemblyDescriptionAttribute("A 9P Client/Server Library written in C#")]
[assembly: GuidAttribute("12dd4614-0f72-4deb-a9d1-37d825b9a07b")]
[assembly: AssemblyCompanyAttribute("Docker")]
[assembly: AssemblyCopyrightAttribute("Copyright © Docker, Inc. 2016")]
[assembly: AssemblyVersionAttribute("0.1.6.9999")]
[assembly: AssemblyFileVersionAttribute("0.1.6.9999")]
[assembly: AssemblyMetadataAttribute("githash","6a92cb")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Sharp9P";
        internal const System.String AssemblyDescription = "A 9P Client/Server Library written in C#";
        internal const System.String Guid = "12dd4614-0f72-4deb-a9d1-37d825b9a07b";
        internal const System.String AssemblyCompany = "Docker";
        internal const System.String AssemblyCopyright = "Copyright © Docker, Inc. 2016";
        internal const System.String AssemblyVersion = "0.1.6.9999";
        internal const System.String AssemblyFileVersion = "0.1.6.9999";
        internal const System.String AssemblyMetadata_githash = "6a92cb";
    }
}
