// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Datakit")]
[assembly: AssemblyDescriptionAttribute("C# Datakit Bindings")]
[assembly: GuidAttribute("58F47959-A6E8-4433-A94A-61DBCC01A1E8")]
[assembly: AssemblyCompanyAttribute("Docker")]
[assembly: AssemblyCopyrightAttribute("Copyright © Docker, Inc. 2016")]
[assembly: AssemblyVersionAttribute("0.1.0.9999")]
[assembly: AssemblyFileVersionAttribute("0.1.0.9999")]
[assembly: AssemblyMetadataAttribute("githash","6a92cb")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Datakit";
        internal const System.String AssemblyDescription = "C# Datakit Bindings";
        internal const System.String Guid = "58F47959-A6E8-4433-A94A-61DBCC01A1E8";
        internal const System.String AssemblyCompany = "Docker";
        internal const System.String AssemblyCopyright = "Copyright © Docker, Inc. 2016";
        internal const System.String AssemblyVersion = "0.1.0.9999";
        internal const System.String AssemblyFileVersion = "0.1.0.9999";
        internal const System.String AssemblyMetadata_githash = "6a92cb";
    }
}
