version: '2'
volumes:
  session_data:
services:
  ci:
    restart: always
    build: .
    command: --metadata-store tcp:datakit:5640 --web-ui=https://datakit.ci:8446/ --sessions-backend=redis://redis
    ports:
     - "8446:8443"
    volumes:
     - ./data/ci/repos:/data/repos
     - ./data/ci/secrets:/secrets
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
     - datakit
     - redis
  datakit:
    restart: always
    image: docker/datakit
    user: "root"
    volumes:
      - ./data/datakit/data:/data
      - ./data/datakit/_ssh:/root/.ssh
    command: --git /data --listen-9p tcp://0.0.0.0:5640 --auto-push git@github.com:docker/datakit.logs
  bridge:
    restart: always
    image: docker/datakit:github
    command: --datakit tcp://datakit:5640 --no-listen -v -c "*:r,status[ci/datakit]:x,webhook:rw" --webhook http://hooks.datakit.ci:81
    ports:
     - "81:81"
    volumes:
      - ./data/bridge/_github:/root/.github
    depends_on:
     - datakit
  redis:
    restart: always
    image: redis
    command: redis-server --save 60 1
    volumes:
      - session_data:/data
